name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  native-tests:
    name: Native host tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pull submodules
      run: git config --global url."https://github.com/".insteadOf "git@github.com:" && git submodule update --init --recursive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run host tests
      run: cargo test --manifest-path rtsched/Cargo.toml --target x86_64-unknown-linux-gnu

  cortex-m-builds:
    name: Cortex-M builds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pull submodules
      run: git config --global url."https://github.com/".insteadOf "git@github.com:" && git submodule update --init --recursive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install embedded Rust target
      run: rustup target add thumbv8m.main-none-eabihf
    - name: Build LPC55S69 board binary
      run: cargo build --release -p lpc55s69
    - name: Build rtsched Cortex-M examples
      env:
        RUSTFLAGS: -L boards/lpc55s69
      run: cargo build --manifest-path rtsched/Cargo.toml --examples --features embedded-examples --target thumbv8m.main-none-eabihf
